#ifndef FIRMWARE_CONFIG_H
#define FIRMWARE_CONFIG_H

#define FIRMWARE_ROLE_USB_DONGLE  0
#define FIRMWARE_ROLE_DAPLINK     1

#ifndef FIRMWARE_ROLE
#define FIRMWARE_ROLE FIRMWARE_ROLE_DAPLINK
#endif

#if (FIRMWARE_ROLE != FIRMWARE_ROLE_USB_DONGLE) && \
    (FIRMWARE_ROLE != FIRMWARE_ROLE_DAPLINK)
#error "FIRMWARE_ROLE must be 0 (USB Dongle) or 1 (DAPLink)"
#endif

#endif
